// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/feedback-studio/FeedbackStudio.tsx": () => import("../components/mockups/feedback-studio/FeedbackStudio.tsx"),
  "./components/mockups/feedback-studio/HerzbackLiveVariant.tsx": () => import("../components/mockups/feedback-studio/HerzbackLiveVariant.tsx")
};
